### ISSUE TITLE
Ethernet not working

### ISSUE THREAD

**Issue by petrus091** [huukhai/hackintosh-rog-b550i#11]
Hi, i'm using your efi , and anything else is working well but Ethernet , my lan is Realtek RTL8125 2.5GBit Ethernet , could you give some help ?

**Comment by dabeeeenster** [comment]
I have the LAN working with the standard EFI in this repo but I do get packet loss - apparently the same thing happens in Windows.

**Comment by petrus091** [comment]
thks , i'v solved it by inject LucyRTL8125Ethernet.kext. and it's working well
