### ISSUE TITLE
I225-v issues

### ISSUE THREAD

**Issue by The1NdNly** [huukhai/hackintosh-rog-b550i#6]
Hello, I'm a first-timer setting up a Hackintosh & ive been having some issues with getting it to install. It seems that whatever I do my I225-v ethernet controller isn't working so I cannot install it from the backup server. I'm running a system close to your own (strix b550-e, 5900x, 32gb 3600mhz, gtx 1060) and I have followed a few different b550 guides along with the open-core guide with no luck, I've also tried using your pack along with taking some of your Kexts and merging them into my own EFI file with no luck. I'm a little lost after trying this for 2 days if I'm honest. I notice in the guide it says 

"For Intel's i225-V NICs, patches are mentioned in the desktop Comet Lake DeviceProperty section. No kext is required.Requires macOS 10.15 or newer"

https://dortania.github.io/OpenCore-Install-Guide/ktext.html#ethernet
 and mentions the patch to use here 
https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#deviceproperties

I'm starting to wonder if it's not possible in MacOS HS (10.13.6) as this is the latest version I can use due to my GFX card and no IGPU. 

Any help, guidance or advice you could give would be highly appreciated! at this point id be happy to pay or donate something for some help!

A post with some more info, driver, kexts & plist can be found on reddit where I also asked.
https://www.reddit.com/r/hackintosh/comments/kccumo/asus_strix_b550e_intel_i225v_ethernet_issues/

Many thanks & kind regards.

**Comment by iam4x** [comment]
Hi,

I'm not sure for Mac OS 10.13.6 but for the ethernet to work you need at least these two kext: 

![image](https://user-images.githubusercontent.com/893837/102080034-0a683d80-3e0e-11eb-9f24-116c03b74e30.png)

And to have this `DeviceProperties` in your opencore config:

```
	<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x8,0x1)/Pci(0x0,0x4)</key>
			<dict>
				<key>layout-id</key>
				<integer>3</integer>
			</dict>
			<key>PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x2)/Pci(0x9,0x0)/Pci(0x0,0x0)</key>
			<dict>
				<key>built-in</key>
				<data>AQ==</data>
				<key>device-id</key>
				<data>8hUAAA==</data>
			</dict>
			<key>PciRoot(0x0)/Pci(0x1,0x1)/Pci(0x0,0x0)</key>
			<dict>
				<key>built-in</key>
				<data>AQ==</data>
			</dict>
		</dict>
		<key>Delete</key>
		<dict/>
	</dict>
```

(see theses lines https://github.com/huukhai/hackintosh-rog-b550i/blob/master/EFI/OC/config.plist#L193-L217)

**Comment by iam4x** [comment]
You can check out my up to date fork working on Catalina (this repo supports BigSur) https://github.com/iam4x/opencore-efi-b550i-strix

**Comment by The1NdNly** [comment]
Hey! Thanks for the quick update!
unfortunately, I've tried this already. Just for a sanity check I just tried again, I copied both kexts from this repo over and added in the exact same device properties in the plist but I still have no ethernet at the installation phase to DL & install.
I'm just going to try using your Cata version with HS to see if that will work. 

[config.txt](https://github.com/huukhai/hackintosh-rog-b550i/files/5689194/config.txt)
![image](https://user-images.githubusercontent.com/7751064/102089892-b3b23200-3e14-11eb-92eb-c718d6ec88c0.png)
![image](https://user-images.githubusercontent.com/7751064/102089916-bad94000-3e14-11eb-9a29-031123d8e0cb.png)

I was recommended to try and install HS with an offline installer and try to fix it later, however, GibMacOS downloads the extracted .dmg and it's included software that makes the usb for you (with opencore over clover) seems to be broken as I cannot get past the kernel loading screen no matter what EFI I use.

my only other "option" is to dig out my old GTX 660TI as I believe they support up to current-gen. however, I don't think my PSU has enough 8pins left to power it and I'm not 100% sure how to go about having my 1060 active in windows while my 660 is active in mac, however, I think it's possible just another step and an annoyance to swap cables, and potentially cards (if I don't have the psu cables).

I'll report back after trying the cata version on HS. Hopefully, I can get this running as-is.  

Many thanks & kind regards!

**Comment by The1NdNly** [comment]
Just Tried your EFI as it was, still get the same issue with no Inet at the installer. your EFI seems to save some debug info at the root, not much to see inside, however, there is something relating to WIFI which I haven't been able to get working either. 
```

00:000 00:000 OC: Prelinked injection SMCAMDProcessor.kext () - Invalid Parameter
00:057 00:057 OC: Prelinked injection AirportItlwm.kext () - Invalid Parameter
```

**Comment by iam4x** [comment]
You may need other boot arguments, can you check https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/nvidia-gpu.html#pascal-series-gtx-10xx which should help to get your 1060 working.

What are the last log lines of open core boot?

**Comment by The1NdNly** [comment]
Hey! ive been playing around all day with it, nothing i did using HS worked. In the end i gave in and dug out my old 660TI and downloaded Cata along with your EFI. i swapped out my 1060 and used my 660 in slot 2 due to not having enough 6pins (need 2 extra for the 660) and everything worked "Right out of the box".. the 660 is old and now i remember it overheats fast. Anyway the plan until just now was to upgrade my psu and call it a day but after swapping out my cards and going to boot back into windows but booting into mac instead i can say the 1060 is working mostly fine so far videos are a little choppy at point and the systems feels a little laggy but i dont have the web driver kext right now so i have hope it will get me by.

the only thing thats not working for me out of the box is my USB ports. Currently only two are working but if i remember i read somewhere that you need to change some settings to get the rest to work.

**Comment by huukhai** [comment]
> Hi,
> 
> I'm not sure for Mac OS 10.13.6 but for the ethernet to work you need at least these two kext:
> 
> ![image](https://user-images.githubusercontent.com/893837/102080034-0a683d80-3e0e-11eb-9f24-116c03b74e30.png)
> 
> And to have this `DeviceProperties` in your opencore config:
> 
> ```
> 	<key>DeviceProperties</key>
> 	<dict>
> 		<key>Add</key>
> 		<dict>
> 			<key>PciRoot(0x0)/Pci(0x8,0x1)/Pci(0x0,0x4)</key>
> 			<dict>
> 				<key>layout-id</key>
> 				<integer>3</integer>
> 			</dict>
> 			<key>PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x2)/Pci(0x9,0x0)/Pci(0x0,0x0)</key>
> 			<dict>
> 				<key>built-in</key>
> 				<data>AQ==</data>
> 				<key>device-id</key>
> 				<data>8hUAAA==</data>
> 			</dict>
> 			<key>PciRoot(0x0)/Pci(0x1,0x1)/Pci(0x0,0x0)</key>
> 			<dict>
> 				<key>built-in</key>
> 				<data>AQ==</data>
> 			</dict>
> 		</dict>
> 		<key>Delete</key>
> 		<dict/>
> 	</dict>
> ```
> 
> (see theses lines https://github.com/huukhai/hackintosh-rog-b550i/blob/master/EFI/OC/config.plist#L193-L217)


This is correct, pls note that, the above DeviceProperties info is needed.

**Comment by The1NdNly** [comment]
> > Hi,
> > I'm not sure for Mac OS 10.13.6 but for the ethernet to work you need at least these two kext:
> > ![image](https://user-images.githubusercontent.com/893837/102080034-0a683d80-3e0e-11eb-9f24-116c03b74e30.png)
> > And to have this `DeviceProperties` in your opencore config:
> > ```
> > 	<key>DeviceProperties</key>
> > 	<dict>
> > 		<key>Add</key>
> > 		<dict>
> > 			<key>PciRoot(0x0)/Pci(0x8,0x1)/Pci(0x0,0x4)</key>
> > 			<dict>
> > 				<key>layout-id</key>
> > 				<integer>3</integer>
> > 			</dict>
> > 			<key>PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x2)/Pci(0x9,0x0)/Pci(0x0,0x0)</key>
> > 			<dict>
> > 				<key>built-in</key>
> > 				<data>AQ==</data>
> > 				<key>device-id</key>
> > 				<data>8hUAAA==</data>
> > 			</dict>
> > 			<key>PciRoot(0x0)/Pci(0x1,0x1)/Pci(0x0,0x0)</key>
> > 			<dict>
> > 				<key>built-in</key>
> > 				<data>AQ==</data>
> > 			</dict>
> > 		</dict>
> > 		<key>Delete</key>
> > 		<dict/>
> > 	</dict>
> > ```
> > 
> > 
> > (see theses lines https://github.com/huukhai/hackintosh-rog-b550i/blob/master/EFI/OC/config.plist#L193-L217)
> 
> This is correct, pls note that, the above DeviceProperties info is needed.


Hi huukhai, Thanks for the reply.

It seems that the correct answer is that the I225-v isnt supported in any version of MacOS < 10.15. I have tried every combo of setting the internet has offered to me and nothing has worked. However, as soon as I upgraded to HS it worked like a charm.
